name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # 👈 required for pushing changes to the repo

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout
